# Generated by Django 3.0.3 on 2020-08-12 15:10

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='project_text',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_creators',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_direction',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_root',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_state',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_text_conclusions',
            field=django_summernote.fields.SummernoteTextField(default='', verbose_name='project text conclusions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_text_discussions',
            field=django_summernote.fields.SummernoteTextField(default='', verbose_name='project text discussions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_text_methods',
            field=django_summernote.fields.SummernoteTextField(default='', verbose_name='project text methods'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_text_results',
            field=django_summernote.fields.SummernoteTextField(default='', verbose_name='project text results'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_text_task',
            field=django_summernote.fields.SummernoteTextField(default='', verbose_name='project text task'),
            preserve_default=False,
        ),
    ]
