# Generated by Django 3.0.3 on 2021-07-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_auto_20210717_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='project_popularity',
            field=models.IntegerField(default=0),
        ),
    ]
