# Generated by Django 3.0.6 on 2020-09-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0002_auto_20200812_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='project_wins',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
