# Generated by Django 3.0.6 on 2020-10-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0003_projectinfo_project_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='project_wins',
        ),
    ]
