# Generated by Django 3.0.3 on 2021-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0003_projectinfo_project_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='project_iseng',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
