# Generated by Django 3.0.3 on 2021-07-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0004_projectinfo_project_iseng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='project_short',
            field=models.CharField(max_length=200),
        ),
    ]
