# Generated by Django 3.0.6 on 2021-02-21 15:50

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0004_remove_projectinfo_project_wins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='project_text_conclusions',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='project_text_discussions',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='project_text_methods',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='project_text_results',
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='project_text_task',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_short',
            field=django_summernote.fields.SummernoteTextField(default=123, verbose_name='project short'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_text',
            field=django_summernote.fields.SummernoteTextField(default=123, verbose_name='project text'),
            preserve_default=False,
        ),
    ]
