# Generated by Django 3.0.3 on 2021-07-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dappx', '0005_auto_20210718_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='project_short',
            field=models.CharField(default='', max_length=200),
        ),
    ]
